configuration:
  # Enable expansion for Bicep module from parameter files.
  AZURE_PARAMETER_FILE_EXPANSION: true

input:
  pathIgnore:
  # Exclude bicepconfig.json
  - 'bicepconfig.json'
  # Exclude module files
  - '.modules/**/*.bicep'
  - '.github/*'

rule:
  exclude:
  - Azure.Resource.UseTags
  - Azure.VM.UseHybridUseBenefit