name: Validate

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Analyze Azure template files
        uses: microsoft/ps-rule@v2.5.0
        with:
          modules:  "PSRule.Rules.Azure"
          outputFormat: Sarif
          outputPath: reports/ps-rule-results.sarif
          option: .github/ps-rule.yaml

      - name: Upload results to security tab
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: reports/ps-rule-results.sarif
