name: Validate

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Analyze Azure template files
        uses: microsoft/ps-rule@v2.4.2
        with:
          modules: 'PSRule.Rules.Azure'
          inputPath: source/webapp/
          outputFormat: sarif

